Entrega módulo MVC
elagarrigue/AyDS22-AK-NewYork2 pull request #4
Opened 2022-05-10 00:04 UTC by FacundoAlvarado9

Hacemos la entrega del módulo MVC.

El diagrama está en la carpeta /docs.

Cualquier consulta, estamos a disposición. Saludos.

2022-05-12 13:34 UTC, kevschweitzer requested changes

2022-05-12 13:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/model/repository/external/nytimes/NYTimesToArtistResolverImpl.kt
> +        return try{
```suggestion
        return try {
```

2022-05-12 13:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/model/repository/local/nytimes/sqldb/CursorToArtistInfoMapper.kt
> +        if(cursor.moveToNext()){
```suggestion
        if(cursor.moveToNext()) {
```

2022-05-12 13:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/view/ArtistInfoDescriptionHelperImpl.kt
> +private const val ASTERISK = "[*]"
Mejor nombre sería LOCALLY_STORED_SYMBOL o algo que represente que significa y no solo lo que es

2022-05-12 13:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/view/ArtistInfoDescriptionHelperImpl.kt
> +        val toReturn : String = when (artist) {
toReturn no se retorna. Elegir otro nombre como rawArtistInfoText

2022-05-12 13:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/view/ArtistInfoDescriptionHelperImpl.kt
> +                (if (artist.isLocallyStored) ASTERISK else "") + " ${artist.artistInfo} "
```suggestion
                "{if (artist.isLocallyStored) ASTERISK else "" }  ${artist.artistInfo} "
```

2022-05-12 13:34 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/view/ArtistInfoDescriptionHelperImpl.kt
> +        stringBuilder.append("<html><div width=400>")
Extraer los bloques HTML a constantes tipo HEADER, FONT, etc. La constante 400 tambien expresarla como constrante witdth

2022-05-12 22:02 UTC, danidema commented on app/src/main/java/ayds/newyork/songinfo/moredetails/view/ArtistInfoDescriptionHelperImpl.kt
> +                (if (artist.isLocallyStored) ASTERISK else "") + " ${artist.artistInfo} "
"{if (artist.isLocallyStored) ASTERISK else "" }  ${artist.artistInfo} " 
esto así como esta no funciona, no entendemos el cambio

2022-05-13 20:10 UTC, kevschweitzer requested changes
Diagrama:

En el diagrama fijense que las implementaciones siguientes no son necesarias que estén ya que se sobre entienden y ensucian el diagrama
MoreDetailsModelImpl
ArtistInfoRepositoryImpl
NYTimestoArtistResolverImpl
NYTimesTableConstants y CursorToArtsitInfoMapper (implementaciones)

2022-05-13 20:10 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/model/repository/local/nytimes/NYTimesLocalStorage.kt
> +    fun getArtistById(id : String) : ArtistInfo?
No se usa

2022-05-13 20:10 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/view/ArtistInfoDescriptionHelperImpl.kt
> +                (if (artist.isLocallyStored) LOCALLY_STORED_SYMBOL else "") + " ${artist.artistInfo} "
Me había faltado un signo de pesos anteriormente. En Kotlin se evita el uso de concatenación porque hay otras herramientas. Se puede definir un string y dentro del mismo resolver diferentes partes de código. Para poner una variable dentro de un string se utiliza $variable y para un bloque de código se usa ${bloque de codigo}. Para este caso sería
"${if (artist.isLocallyStored) LOCALLY_STORED_SYMBOL else "" }  ${artist.artistInfo}"

Fijense si les anda sino no importa, es una corrección menor, pero para que vean como se haría normalmente

2022-05-14 17:02 UTC, kevschweitzer approved these changes

2022-05-14 17:02 UTC, merged