Entrega: Abstracción e Integración servicio externo
elagarrigue/AyDS22-AK-NewYork2 pull request #6
Opened 2022-06-05 21:43 UTC by FacundoAlvarado9

Hacemos entrega del último módulo.

Para mostrar las cards elegimos la propuesta de tener un botón que itere sobre las cards.

Saludos

2022-06-06 13:36 UTC, kevschweitzer requested changes
todo mal

2022-06-06 15:56 UTC, danidema commented
Realizamos todas las correcciones anotadas.

2022-06-07 15:31 UTC, kevschweitzer requested changes
Para el diagrama sacar la carpeta Libs (es una organización interna) y dejar los servicios sueltos. Además para el servicio propio hacer el diagrama interno

agregar tests para proxy y broker

2022-06-07 15:31 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/controller/MoreDetailsController.kt
> +    private fun updateIndex() {
No es necesario un evento individual de updateIndex(). El indice se puede actualizar al llamar a la next card

2022-06-07 15:31 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/model/repository/external/LastFMProxy.kt
> +        var card : Card? = null
Se puede simplificar
```
return try{
            lastFmService.getArtistBio(name)?.let{ mapCard(it) }
        } catch(e : Exception){
            null
        }
 ```
 
 Hacer en todos

2022-06-07 15:31 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/model/repository/external/WikipediaDataProxy.kt
> +    override fun getCard(name: String): Card? {
idem anterior

2022-06-07 15:31 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/model/repository/external/NewYorkTimesProxy.kt
> +    override fun getCard(name: String): Card? {
idem anterior

2022-06-07 15:31 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/view/ArtistInfoDescriptionHelperImpl.kt
> +    fun getCardText(artist: Card = EmptyCard) : String
Tienen un método implicito acá. Están usando el parametro por defecto para llamar a otro método.
Seria correcto tener 2 metodos, uno que ea getCardText y otro que sea getNotFoundText (por ejemplo), ya que ustedes desde la vista saben a que están llamando cuando lo llaman con o sin parametro

2022-06-07 15:31 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/view/MoreDetailsView.kt
> +    private fun getSource(source : Source?) : String{
Hacer que source sea un enum con un dato asociado evita necesitar esto

```
enum class Source (value: String) {
  LASTFM("LASTFM"),
  ...
}

2022-06-07 15:31 UTC, kevschweitzer commented on app/src/test/java/ayds/newyork/songinfo/moredetails/model/repository/CardRepositoryImplTest.kt
> +        val card1 = ExternalCard(
Cuando en los test se van a usar muchas cards iguales se crean globalmente. Hagan una lista global y en @Before le agregan a la lista las cards (pueden crear una sola e ir cambiandole el source para agregarla)

2022-06-10 02:44 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/model/entities/Source.kt
> +enum class Source(value : String) {
definir el value como val y sacar el get y el text.

```
enum class Source(val value : String) {
    LASTFM(TEXTO_LASTFM),
    WIKIPEDIA(TEXTO_WIKIPIEDIA),
    NEWYORKTIMES(TEXTO_NEWYORKTIMES)
   }

```

Asi deberia andar

2022-06-10 02:53 UTC, kevschweitzer commented on app/src/test/java/ayds/newyork/songinfo/moredetails/model/repository/WikipediaDataProxyTest.kt
> +    fun `given existing artist by name should return a card`(){
Este metodo esta verificando el mapper. Eso está bien pero además deberian agregar un verify que chequee que se está llamando al metodo del servicio externo. Igual para todos los proxies

2022-06-10 02:55 UTC, kevschweitzer commented on app/src/test/java/ayds/newyork/songinfo/moredetails/model/repository/BrokerTest.kt
> +    fun `given an artistName it should call all proxies`() {
Tienen que verificar que para cada proxy se llame al metodo de la interfaz

2022-06-13 00:55 UTC, kevschweitzer approved these changes

2022-06-13 00:55 UTC, merged